apiVersion: v1
kind: Service
metadata:
  name: {{ include "lps-adapter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lps-adapter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.AppVersion | replace "+" "_" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.containers.api.service.ports }}
    - port: {{ $port.externalPort }}
      targetPort: {{ $port.internalPort }}
      protocol: TCP
      name: {{ $port.name }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "lps-adapter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
